package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Chanel generated by hbm2java
 */
public class Chanel  implements java.io.Serializable {


     private int chanelId;
     private String chanelName;
     private String chanelImage;
     private String chanelContent;
     private float chanelPrice;
     private byte type;
     private Set packageses = new HashSet(0);

    public Chanel() {
    }
    public Chanel(int chanelId){
        this.chanelId=chanelId;
    }
    public Chanel(String chanelName, String chanelImage, String chanelContent,float chanelPrice,byte type, Set packageses) {
       this.chanelName = chanelName;
       this.chanelImage = chanelImage;
       this.chanelContent = chanelContent;
       this.chanelPrice=chanelPrice;
       this.type=type;
       this.packageses = packageses;
    }

    public float getChanelPrice() {
        return chanelPrice;
    }

    public void setChanelPrice(float chanelPrice) {
        this.chanelPrice = chanelPrice;
    }

    public byte getType() {
        return type;
    }

    public void setType(byte type) {
        this.type = type;
    }
   
    public int getChanelId() {
        return this.chanelId;
    }
    
    public void setChanelId(int chanelId) {
        this.chanelId = chanelId;
    }
    public String getChanelName() {
        return this.chanelName;
    }
    
    public void setChanelName(String chanelName) {
        this.chanelName = chanelName;
    }
    public String getChanelImage() {
        return this.chanelImage;
    }
    
    public void setChanelImage(String chanelImage) {
        this.chanelImage = chanelImage;
    }
    public String getChanelContent() {
        return this.chanelContent;
    }
    
    public void setChanelContent(String chanelContent) {
        this.chanelContent = chanelContent;
    }
    public Set getPackageses() {
        return this.packageses;
    }
    
    public void setPackageses(Set packageses) {
        this.packageses = packageses;
    }




}


