package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String customerId;
     private String cusName;
     private String address;
     private String phone;
     private String email;
     private Date endDate;
     private String username;
     private String password;
     private String bankCardNumber;
     private Byte status;
     private Set orders = new HashSet(0);
     private Set feedbacks = new HashSet(0);
     private Set requirements = new HashSet(0);

    public Customer() {
    }

    public Customer(String cusName, String address, String phone, String email, Date endDate, String username, String password, String bankCardNumber, Byte status, Set orders, Set feedbacks, Set requirements) {
       this.cusName = cusName;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.endDate = endDate;
       this.username = username;
       this.password = password;
       this.bankCardNumber = bankCardNumber;
       this.status = status;
       this.orders = orders;
       this.feedbacks = feedbacks;
       this.requirements = requirements;
    }
   
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getCusName() {
        return this.cusName;
    }
    
    public void setCusName(String cusName) {
        this.cusName = cusName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getBankCardNumber() {
        return this.bankCardNumber;
    }
    
    public void setBankCardNumber(String bankCardNumber) {
        this.bankCardNumber = bankCardNumber;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Set getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set feedbacks) {
        this.feedbacks = feedbacks;
    }
    public Set getRequirements() {
        return this.requirements;
    }
    
    public void setRequirements(Set requirements) {
        this.requirements = requirements;
    }




}


