package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distributor generated by hbm2java
 */
public class Distributor  implements java.io.Serializable {


     private int distributorId;
     private String disName;
     private String disAddress;
     private String disEmail;
     private String disPhone;
     private Byte status;
     private String username;
     private String password;
     private Set products = new HashSet(0);

    public Distributor() {
    }

    public Distributor(int distributorId) {
        this.distributorId = distributorId;
    }

    public Distributor(String disName, String disAddress, String disEmail, String disPhone, Byte status, String username, String password, Set products) {
       this.disName = disName;
       this.disAddress = disAddress;
       this.disEmail = disEmail;
       this.disPhone = disPhone;
       this.status = status;
       this.username = username;
       this.password = password;
       this.products = products;
    }
   
    public int getDistributorId() {
        return this.distributorId;
    }
    
    public void setDistributorId(int distributorId) {
        this.distributorId = distributorId;
    }
    public String getDisName() {
        return this.disName;
    }
    
    public void setDisName(String disName) {
        this.disName = disName;
    }
    public String getDisAddress() {
        return this.disAddress;
    }
    
    public void setDisAddress(String disAddress) {
        this.disAddress = disAddress;
    }
    public String getDisEmail() {
        return this.disEmail;
    }
    
    public void setDisEmail(String disEmail) {
        this.disEmail = disEmail;
    }
    public String getDisPhone() {
        return this.disPhone;
    }
    
    public void setDisPhone(String disPhone) {
        this.disPhone = disPhone;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


