package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1



/**
 * Faq generated by hbm2java
 */
public class Faq  implements java.io.Serializable {


     private int faqId;
     private String faqQestion;
     private String faqAnswer;
     private Byte status;

    public Faq() {
    }

    public Faq(int faqId) {
        this.faqId = faqId;
    }

    public Faq(String faqQestion, String faqAnswer, Byte status) {
       this.faqQestion = faqQestion;
       this.faqAnswer = faqAnswer;
       this.status = status;
    }
   
    public int getFaqId() {
        return this.faqId;
    }
    
    public void setFaqId(int faqId) {
        this.faqId = faqId;
    }
    public String getFaqQestion() {
        return this.faqQestion;
    }
    
    public void setFaqQestion(String faqQestion) {
        this.faqQestion = faqQestion;
    }
    public String getFaqAnswer() {
        return this.faqAnswer;
    }
    
    public void setFaqAnswer(String faqAnswer) {
        this.faqAnswer = faqAnswer;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


