package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;

/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private int feedId;
     private Customer customer;
     private String feedTitle;
     private String feedContent;
     private Timestamp feedDate;
     private String feedReply;
     private Byte status;

    public Feedback() {
    }

    public Feedback(Customer customer, String feedTitle, String feedContent, Timestamp feedDate, String feedReply, Byte status) {
       this.customer = customer;
       this.feedTitle = feedTitle;
       this.feedContent = feedContent;
       this.feedDate = feedDate;
       this.feedReply = feedReply;
       this.status = status;
    }
   
    public int getFeedId() {
        return this.feedId;
    }
    
    public void setFeedId(int feedId) {
        this.feedId = feedId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getFeedTitle() {
        return this.feedTitle;
    }
    
    public void setFeedTitle(String feedTitle) {
        this.feedTitle = feedTitle;
    }
    public String getFeedContent() {
        return this.feedContent;
    }
    
    public void setFeedContent(String feedContent) {
        this.feedContent = feedContent;
    }
    public Timestamp getFeedDate() {
        return this.feedDate;
    }
    
    public void setFeedDate(Timestamp feedDate) {
        this.feedDate = feedDate;
    }
    public String getFeedReply() {
        return this.feedReply;
    }
    
    public void setFeedReply(String feedReply) {
        this.feedReply = feedReply;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


