package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1



/**
 * OderDetail generated by hbm2java
 */
public class OderDetail  implements java.io.Serializable {


     private OderDetailId id;
     private Order order;
     private Packages packages;
     private double price;
     private int quantity;

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public OderDetail() {
    }

    public OderDetail(OderDetailId id, Order order, Packages packages, double price,int quantity) {
       this.id = id;
       this.order = order;
       this.packages = packages;
       this.price = price;
       this.quantity=quantity;
    }
   
    public OderDetailId getId() {
        return this.id;
    }
    
    public void setId(OderDetailId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Packages getPackages() {
        return this.packages;
    }
    
    public void setPackages(Packages packages) {
        this.packages = packages;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

}


