package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1



/**
 * OderDetailId generated by hbm2java
 */
public class OderDetailId  implements java.io.Serializable {


     private int oderId;
     private int packageId;

    public OderDetailId() {
    }

    public OderDetailId(int oderId, int packageId) {
       this.oderId = oderId;
       this.packageId = packageId;
    }
   
    public int getOderId() {
        return this.oderId;
    }
    
    public void setOderId(int oderId) {
        this.oderId = oderId;
    }
    public int getPackageId() {
        return this.packageId;
    }
    
    public void setPackageId(int packageId) {
        this.packageId = packageId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OderDetailId) ) return false;
		 OderDetailId castOther = ( OderDetailId ) other; 
         
		 return (this.getOderId()==castOther.getOderId())
 && (this.getPackageId()==castOther.getPackageId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOderId();
         result = 37 * result + this.getPackageId();
         return result;
   }   


}


