package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int oderId;
     private Customer customer;
     private Date orderPaymentDate;
     private Date orderExpiredDate;
     private Byte status;
     private Set oderDetails = new HashSet(0);

    public Order() {
    }

    public Order(Customer customer, Date orderPaymentDate, Date orderExpiredDate, Byte status, Set oderDetails) {
       this.customer = customer;
       this.orderPaymentDate = orderPaymentDate;
       this.orderExpiredDate = orderExpiredDate;
       this.status = status;
       this.oderDetails = oderDetails;
    }
   
    public int getOderId() {
        return this.oderId;
    }
    
    public void setOderId(int oderId) {
        this.oderId = oderId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Date getOrderPaymentDate() {
        return this.orderPaymentDate;
    }
    
    public void setOrderPaymentDate(Date orderPaymentDate) {
        this.orderPaymentDate = orderPaymentDate;
    }
    public Date getOrderExpiredDate() {
        return this.orderExpiredDate;
    }
    
    public void setOrderExpiredDate(Date orderExpiredDate) {
        this.orderExpiredDate = orderExpiredDate;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Set getOderDetails() {
        return this.oderDetails;
    }
    
    public void setOderDetails(Set oderDetails) {
        this.oderDetails = oderDetails;
    }




}


