package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Packages generated by hbm2java
 */
public class Packages implements java.io.Serializable {

    private int packageId;
    private String packageName;
    private String packageImage;
    private String packageContent;
    private Double packagePrice = 0d;
    private int packageMonth;
    private Byte status;
    private Byte type;
    private Set chanels = new HashSet(0);
    private Set oderDetails = new HashSet(0);

    public Packages() {
    }

    public Packages(String packageName, String packageImage, String packageContent, Double packagePrice, Byte status, Byte type, Set chanels, Set oderDetails) {
        this.packageName = packageName;
        this.packageImage = packageImage;
        this.packageContent = packageContent;
        this.packagePrice = packagePrice;
        this.status = status;
        this.type = type;
        this.chanels = chanels;
        this.oderDetails = oderDetails;
    }

    public int getPackageMonth() {
        return packageMonth;
    }

    public void setPackageMonth(int packageMonth) {
        this.packageMonth = packageMonth;
    }

    public int getPackageId() {
        return this.packageId;
    }

    public void setPackageId(int packageId) {
        this.packageId = packageId;
    }

    public String getPackageName() {
        return this.packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getPackageImage() {
        return this.packageImage;
    }

    public void setPackageImage(String packageImage) {
        this.packageImage = packageImage;
    }

    public String getPackageContent() {
        return this.packageContent;
    }

    public void setPackageContent(String packageContent) {
        this.packageContent = packageContent;
    }

    public Double getPackagePrice() {
        return this.packagePrice;
    }

    public void setPackagePrice(Double packagePrice) {
        this.packagePrice = packagePrice;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Byte getType() {
        return this.type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public Set getChanels() {
        return this.chanels;
    }

    public void setChanels(Set chanels) {
        this.chanels = chanels;
    }

    public Set getOderDetails() {
        return this.oderDetails;
    }

    public void setOderDetails(Set oderDetails) {
        this.oderDetails = oderDetails;
    }

}
