package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int productId;
     private Distributor distributor;
     private String productName;
     private Double productPrice;
     private byte type;
     private Set requirements = new HashSet(0);

    public Product() {
    }

    public Product(Distributor distributor, String productName, Double productPrice, byte type, Set requirements) {
       this.distributor = distributor;
       this.productName = productName;
       this.productPrice = productPrice;
       this.type = type;
       this.requirements = requirements;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Distributor getDistributor() {
        return this.distributor;
    }
    
    public void setDistributor(Distributor distributor) {
        this.distributor = distributor;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Double getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    public Set getRequirements() {
        return this.requirements;
    }
    
    public void setRequirements(Set requirements) {
        this.requirements = requirements;
    }




}


