package entity;
// Generated Jul 1, 2015 8:33:56 AM by Hibernate Tools 4.3.1



/**
 * RequirementId generated by hbm2java
 */
public class RequirementId  implements java.io.Serializable {


     private int productId;
     private String customerId;
     private String serial;

    @Override
    public boolean equals(Object obj) {
        RequirementId tmp=(RequirementId)obj;
        if(tmp.getCustomerId().equals(customerId) && tmp.getProductId()==productId && tmp.getSerial().equals(serial)){
            return true;
        }else{
            return false;
        }
    }

    @Override
    public int hashCode() {
        return productId;
    }

    public RequirementId() {
    }

    public RequirementId(int productId, String customerId, String serial) {
       this.productId = productId;
       this.customerId = customerId;
       this.serial = serial;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }




}


